package com.journeyai.glimpse.models

const val CATEGORY_KEY = "CATEGORY_KEY"
const val Landmarks = "Landmarks"
const val Architecture = "Architecture"
const val Nature = "Nature"
const val Food = "Food"
const val People = "People"
const val Wildlife = "Wildlife"
const val Friends = "Friends"
const val Sunsets = "Sunsets and Sunrises"
const val Festivals = "Festivals and Celebrations"
const val Transportation = "Local Transportation"
const val Religious = "Temples and Religious Symbols"
const val Plants = "Plants"
const val Parks = "Gardens and Parks"
const val Other = "Other"
const val Museums = "Museums and Artifacts"
const val Woman = "Woman"
const val Thames = "Thames"
const val Background = "Background"